name: islami
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg_provider: ^1.0.7
  get_it: ^8.0.3
  go_router: ^14.6.3
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  introduction_screen: ^3.1.14
  prayers_times: ^0.0.5
  shared_preferences: ^2.3.3
  intl: any

  cupertino_icons: ^1.0.8
  flutter_qiblah: ^3.1.0+1
  geolocator: ^13.0.4

dev_dependencies:
  intl_utils: ^2.8.6
  build_runner: ^2.4.11
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  
  

flutter:

  uses-material-design: true
  generate: true


  assets:
    - assets/images/
    - assets/data/
    - assets/sound/azan.mp3
    - assets/sound/notification.wav

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils
  filename: app_images.dart
  field_prefix: null
flutter_intl:
  enabled: true


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#212121"
  adaptive_icon_background: "#212121"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
